/* Generated By:JavaCC: Do not edit this line. PS7CompilerConstants.java */
package ps7;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PS7CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUALS = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int GTHEN = 10;
  /** RegularExpression Id. */
  int LTHEN = 11;
  /** RegularExpression Id. */
  int CMPEQUALS = 12;
  /** RegularExpression Id. */
  int INTTYPE = 13;
  /** RegularExpression Id. */
  int STRINGTYPE = 14;
  /** RegularExpression Id. */
  int BOOLEANTYPE = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int NEWLINE = 18;
  /** RegularExpression Id. */
  int CONSTANT = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int VAR = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int STRING = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"int\"",
    "\"string\"",
    "\"boolean\"",
    "<BOOLEAN>",
    "\"print\"",
    "\"newline\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<VAR>",
    "<LETTER>",
    "<STRING>",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
